# Generated by Django 2.2.10 on 2020-07-06 16:11

import backend.occupations_list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occupations_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='hire_date',
            field=models.DateField(default=backend.occupations_list.models.get_due_date, verbose_name='Дата приема'),
        ),
    ]
