# Generated by Django 2.2.10 on 2020-07-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('occupations_list', '0002_auto_20200704_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupation',
            name='type',
        ),
        migrations.DeleteModel(
            name='OccupationType',
        ),
    ]
